name = "RelaxTime"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Wmzx"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
FastGaussQuadrature = "0.4, 0.5, 1.0"
