uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Wmzx"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
FastGaussQuadrature = "0.4, 0.5, 1.0"
QuadGK = "2"
julia = "1.6"
